<h2>General Settings</h2>
<p>Configure general settings for the curiosity generator.</p>

<table class="form-table">
    <tr>
        <th scope="row">
            <label for="cg_max_curiosities">Max Curiosities</label>
        </th>
        <td>
            <input type="number" name="cg_max_curiosities" id="cg_max_curiosities" class="small-text" min="1" max="20" value="<?php echo esc_attr(get_option('cg_max_curiosities', 20)); ?>" />
            <p class="description">Maximum number of curiosities that can be generated at once (1-20). UPDATED: Now supports up to 20 curiosities.</p>
        </td>
    </tr>
    <tr>
        <th scope="row">
            <label for="cg_min_curiosity_length">Min Curiosity Length</label>
        </th>
        <td>
            <input type="number" name="cg_min_curiosity_length" id="cg_min_curiosity_length" class="small-text" min="50" value="<?php echo esc_attr(get_option('cg_min_curiosity_length', 100)); ?>" />
            <p class="description">Minimum length (in words) for each generated curiosity.</p>
        </td>
    </tr>
    <tr>
        <th scope="row">
            <label for="cg_default_author">Default Author</label>
        </th>
        <td>
            <select name="cg_default_author" id="cg_default_author">
                <?php
                $current_author = get_option('cg_default_author', 1);
                $users = cg_get_users_for_dropdown();
                
                foreach ($users as $user_id => $user_name) {
                    echo '<option value="' . esc_attr($user_id) . '" ' . selected($current_author, $user_id, false) . '>' . esc_html($user_name) . '</option>';
                }
                ?>
            </select>
            <p class="description">The default author for curiosities generated by non-logged-in users. NOTE: All generated posts are now created as PRIVATE by default.</p>
        </td>
    </tr>
</table>